baseURL = "https://slaier.github.io"
enableGitInfo = true
enableEmoji = true
hasCJKLanguage = true
theme = "hugo-book"
timeZone = "Asia/Shanghai"
title = "Slaier's Blog"

defaultContentLanguage = "zh"

[languages]
[languages.en]
  languageName = "English"
  contentDir = "content.en"
  weight = 1
[languages.zh]
  languageName = "中文"
  contentDir = "content.zh"
  weight = 2

[[menu.home]]
  name = "路由交换"
  url = "/docs/switch/ethernet/"
  weight = 1
[[menu.home]]
  name = "Blog"
  url = "/posts/"
  weight = 5
[[menu.home]]
  name = "Github"
  url = "https://github.com/slaier"
  weight = 9
[[menu.after]]
name = "Github"
url = "https://github.com/slaier"
weight = 10

[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/slaier/slaier.github.io'
